/*
Question 1D
Calculate TotalRevenue by fiscal quarter (YYYYQX, ie 2019Q4)
*/

SELECT
AUCTIONS.AUCTIONID,
AUCTIONS.DATE,
MAX(BIDS.BID) * AUCTIONS.VOLUME AS TOTALREVENUE,
BIDS.BIDDERID
FROM
AUCTIONS AS AUCTIONS
INNER JOIN BIDS AS BIDS
ON AUCTIONS.AUCTIONID = BIDS.AUCTIONID
GROUP BY
AUCTIONS.AUCTIONID;


SELECT
    DATE(YEAR || QUARTER) AS DATE
FROM(
    SELECT
        SUBSTR(AUCTIONS.DATE, 1, 4) AS YEAR,
        SUBSTR(AUCTIONS.DATE, 5, 2) AS MONTH,
    FROM
        AUCTIONS);
    
SELECT
QUARTER
TOTAL REVENUE
